name: 05 - 2 - Event Filters and Activity Types
on:
 pull_request:
  type: [closed]
  branch:
  - main

jobs:
 echos:
  runs-on: ubuntu-latest
  steps:
  - name: PR
    run: |
     echo Running whenever a PR is closed