name: 06-context

on:
 workflow_dispatch:

env:
 env1: foo
 env2: bar

jobs:
 echo-data:
   runs-on: ubuntu-latest
   steps:
   - name: Display Information
     run: |
      echo "Event name is ${{ github.event_name }}"
      echo "env1 value is $env1"
      echo "env2 value is $env2"
   - name: reterive Variable
     env:
      env1: bar
      env2: foo
     run: |
      echo "variable value is ${{ vars.MY_VAR }}"
      echo "env1 value is $env1"
      echo "env2 value is $env2"
      