name: using expression
on:
 push:
 workflow_dispatch:
  inputs:
   debug:
    type: boolean
    default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: startup data
      if: ${{ inputs.debug }}
      run: |
        echo "event triggered from ${{ github.event_name }}"
        echo "Branch is ${{ github.ref }}"
        echo "sha is ${{ github.sha }}"
        echo "Runner os is ${{ runner.os }}"
    - name: startup main
      if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
      run: echo "hello world from main"