name: using expression
on:
 push:
 workflow_dispatch:
  inputs:
   debug:
    type: boolean
    default: false
    required: false


echo:
 runs-on: ubuntu-latest
 steps:
 - name: startup data
   if: inputs.debug == true
   run: |
    echo "input debug is true"
- name: startup main
  if: inputs.debug == true && github.ref == main
  run: echo "hello world from main"