name: 08 variables
on:
 push:
 workflow_dispatch:

env:
 WORKFLOW_VAR: "I am workflow env"
 OVERWRITTEN: "I will be overwritten"

jobs:
 echo:
  runs-on: ubuntu-latest
  env:
   JOB_VAR: "I am job var"
   OVERWRITTEN: "job has overwritten"
  steps:
  - name: Print ENV variables
    env:
     STEP_VAR: "I am step var"
     step_vars: "I am another var"
    run: |
     echo "step env var is $STEP_VAR"
     echo "step env var 2 is $step_vars"
     echo "job env var is $JOB_VAR"
     echo "workflow env var is $WORKFLOW_VAR"
     echo "overwritten env var is $OVERWRITTEN"
  - name: Overwrite Job Variable
    run: |
     echo "step env var $OVERWRITTEN"
 