name: 10-execution-flow.yaml
on: 
 workflow_dispatch:
  inputs: 
   pass-unit-tests:
    type: boolean
    default: false

jobs:
 lint-build:
  runs-on: ubuntu-latest
  steps:
  - name: "lint and build"
    run: "echo lint and build"

 unit-test:
  runs-on: ubuntu-latest
  steps:
  - name: "Running unit tests"
    runs: "echo Running unit tests"
  - name: "Failing tests"
    if: ${{ inputs.pass-unit-tests == false }}
    runs: "exit 1"

 deploy-nonprod:
  runs-on: ubuntu-latest
  needs: lint-build,unit-test
  steps:
  - name: "deploy nonprod"
    runs: "echo deploy nonprod"

 e2e-tests:
  runs-on: ubuntu-latest
  needs: deploy-nonprod
  steps:
  - name: "Running E2E tests"
    run: "echo Running E2E tests"

 load-tests:
  runs-on: ubuntu-latest
  needs: deploy-nonprod
  steps:
  - name: Running load tests
    runs: "echo Running load tests"

 deploy-prod:
  runs-on: ubuntu-latest
  needs: e2e-tests,load-tests
  steps:
  - name: "Deploying to prod"
    runs: "echo Deploying to prod"